### ISSUE TITLE
Babel Server Crash

### ISSUE THREAD

**Issue by WenXin20** [tnkmods/Babel#1]
`Minecraft v1.16.5`
`Forge v36.0.7`
`Babel v1.0.4`

When trying to use this mod with Compote, I go a server crash
[Crash Report](https://gist.github.com/WenXin20/da5f4f5d1973989430ffcea72968d1b2)

**Comment by nkirby** [comment]
Thanks for the report, fixed in v1.0.5 which should be available on Curseforge now.

**Comment by nkirby** [comment]
(fixed in 1.0.5)

**Comment by WenXin20** [comment]
Thanks!
